### ISSUE TITLE
Conda build for python 3.9

### ISSUE THREAD

**Issue by perinom** [simonvh/fluff#89]
Hi Simon!

Just installed fluff into a python 3.9 conda environment. Installation runs smooth, but when calling a simple `fluff heatmap` to get the help  it throws :

```
Traceback (most recent call last):
  File "/perino/tools/miniconda3/envs/Perino_2018/bin/fluff", line 7, in <module>
    from fluff.parse import main
  File "/perino/tools/miniconda3/envs/Perino_2018/lib/python3.9/site-packages/fluff/parse.py", line 4, in <module>
    from fluff.commands.heatmap import heatmap
  File "/perino/tools/miniconda3/envs/Perino_2018/lib/python3.9/site-packages/fluff/commands/heatmap.py", line 17, in <module>
    from fluff.plot import heatmap_plot
  File "/perino/tools/miniconda3/envs/Perino_2018/lib/python3.9/site-packages/fluff/plot.py", line 22, in <module>
    GENE_ARROW = ArrowStyle._Curve(beginarrow=False, endarrow=True, head_length=.4, head_width=.4)
TypeError: __init__() got an unexpected keyword argument 'beginarrow'
```

The same happens when installing version 3.0.3, my guess is that by default conda tries to install the last two results of `conda search biofluff`, that have an odd python version in the `build` field. Of course trying to install the py36_0 build on python 3.9 fails.
```
Loading channels: done
# Name                       Version           Build  Channel
biofluff                       2.0.1          py27_1  bioconda
biofluff                       2.0.2          py27_0  bioconda
biofluff                       2.1.0          py27_0  bioconda
biofluff                       2.1.1          py27_0  bioconda
biofluff                       2.1.2          py27_0  bioconda
biofluff                       2.1.3          py27_0  bioconda
biofluff                       3.0.2          py35_0  bioconda
biofluff                       3.0.2          py35_1  bioconda
biofluff                       3.0.2          py36_0  bioconda
biofluff                       3.0.2          py36_1  bioconda
biofluff                       3.0.3          py35_0  bioconda
biofluff                       3.0.3          py36_0  bioconda
biofluff                       3.0.3            py_1  bioconda
biofluff                       3.0.4            py_0  bioconda
```

everything installs and runs fine in a fresh python 3.6 environment, but I was wondering if there's any chance of a new python 3.9 compatible release, it'd be great to be able to install fluff in other more up-to-date environments

**Comment by annrosebright** [comment]
I have the same issue. Is there any solution to this problem? 

Update: I removed -  beginarrow=False, endarrow=True 
from  GENE_ARROW = ArrowStyle._Curve(beginarrow=False, endarrow=True, head_length=.4, head_width=.4)
TypeError: __init__() got an unexpected keyword argument 'beginarrow' and it seems to work. Not sure if that the right way.
